### ISSUE TITLE
REST annotation parity: only Python confirmed in v2.1.0 — track remaining SDKs

### ISSUE THREAD

**Issue by evoludigit** [fraiseql/fraiseql#85]
## Summary

REST transport annotations (`rest_path`, `rest_method`) are only confirmed working in the Python SDK as of v2.1.0. The status across the other 8 SDKs is:

| SDK | Status |
|-----|--------|
| Python | ✅ Confirmed v2.1.0 |
| Go | 🔶 In unreleased commits on `main` |
| Java | 🔶 In unreleased commits on `main` |
| C# | 🔶 In unreleased commits on `main` |
| TypeScript | ❌ Not yet |
| PHP | ❌ Not yet |
| Rust | ❌ Not yet |
| Elixir | ❌ Not yet |
| F# | ❌ Not yet |

## Problem

The SDK index page originally stated "All SDKs support transport annotations for REST and gRPC" — which is incorrect. Users of TypeScript, PHP, Rust, Elixir, or F# SDKs will define `rest_path`/`rest_method` and find their schema compiles fine (the compiler may accept unknown decorator parameters) but no REST endpoints are registered.

This is a silent failure mode: no compile error, no runtime error, just missing REST routes.

## Expected behaviour

1. SDK pages for each language clearly state whether REST annotations are supported in the current release.
2. The compiler should emit a warning (or error) when REST annotations are encountered for an SDK that does not implement them yet.
3. Track Go, Java, and C# REST annotation support to a tagged release.

## Context

Found during documentation review. Related to #70 (REST transport feature tracking).
